{% set version = "1.0.0-1" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-duckdb
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/duckdb_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/duckdb/duckdb_{{ version }}.tar.gz
  sha256: 987edcdcae91dcbc9d554f039425cd23b6e5787e7681f311c9966926744d4ca9

build:
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-dbi                      # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("c") }}            # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]

  host:
    - r-base
    - r-dbi

  run:
    - r-base
    - r-dbi

test:
  commands:
    - $R -e "library('duckdb')"           # [not win]
    - "\"%R%\" -e \"library('duckdb')\""  # [win]

about:
  home: https://duckdb.org
  dev_url: https://github.com/cwida/duckdb
  license: MPL-2.0
  summary: The DuckDB project is an embedded analytical data management system with support for the Structured Query Language (SQL). This package includes all of DuckDB and a R Database Interface (DBI) connector.
  license_family: MOZILLA
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
